version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:05"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 7
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:05"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 7
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:05"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 7
