apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-oppgave-integrasjon
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 8080
  replicas:
    min: 1
    max: 2
  resources:
    requests:
      cpu: 15m
      memory: 256Mi
    limits:
      memory: 512Mi
  kafka:
    pool: "{{ kafka.pool }}"
  azure:
    application:
      enabled: true
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  accessPolicy:
    outbound:
      rules:
        - application: dp-saksbehandling
          namespace: teamdagpenger
        - application: "{{ oppgave.app }}"
          namespace: oppgavehandtering
      external:
        - host: "{{ oppgave.host }}"
  env:
    - name: KAFKA_EXTRA_TOPIC
      value: "{{ oppgavehendelseTopic }}"
    - name: DP_SAKSBEHANDLING_URL
      value: "http://dp-saksbehandling"
    - name: DP_SAKSBEHANDLING_SCOPE
      value: "{{ dpSaksbehandling.scope }}"
    - name: OPPGAVE_URL
      value: "https://{{ oppgave.host }}"
    - name: OPPGAVE_SCOPE
      value: "{{ oppgave.scope }}"
